<a href="https://colab.research.google.com/github/nikhil056/P745/blob/main/Assignment3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
a = []

f = open("Assign3_1.txt", "r")
for line in f.readlines():
  if line[0] == "#":
    continue
  elements = line.split(",")
  elements = [float(x) for x in elements]
  a.append(elements)

f.close()
print(a)

[[1.0, -1.0, 4.0, 0.0, 2.0, 9.0, 19.0], [0.0, 5.0, -2.0, 7.0, 8.0, 4.0, 2.0], [1.0, 0.0, 5.0, 7.0, 3.0, -2.0, 13.0], [6.0, -1.0, 2.0, 3.0, 0.0, 8.0, -7.0], [-4.0, 2.0, 0.0, 5.0, -5.0, 3.0, -9.0], [0.0, 7.0, -1.0, 5.0, 4.0, -2.0, 2.0]]


In [2]:
from numpy import array, zeros, fabs, linalg
a = array([[1,-1,4,0,2,9],
           [0,5,-2,7,8,4],
           [1,0,5,7,3,-2],
           [6,-1,2,3,0,8],
           [-4,2,0,5,-5,3],
           [0,7,-1,5,4,-2]], float)
#the b matrix constant terms of the equations 
b = array([19,2,13,-7,-9,2], float)
n = len(b)
x = zeros(n, float)

#first loop specifys the fixed row
for k in range(n-1):
    if fabs(a[k,k]) < 1.0e-12:
        for i in range(k+1, n):
            if fabs(a[i,k]) > fabs(a[k,k]):
                a[[k,i]] = a[[i,k]]
                b[[k,i]] = b[[i,k]]
                break

 #applies the elimination below the fixed row

    for i in range(k+1,n):
        if a[i,k] == 0:continue

        factor = a[k,k]/a[i,k]
        for j in range(k,n):
            a[i,j] = a[k,j] - a[i,j]*factor
            #we also calculate the b vector of each row
        b[i] = b[k] - b[i]*factor
print(a)
print(b)


x[n-1] = b[n-1] / a[n-1, n-1]
for i in range(n-2, -1, -1):
    sum_ax = 0
  
    for j in range(i+1, n):
        sum_ax += a[i,j] * x[j]
        
    x[i] = (b[i] - sum_ax) / a[i,i]

print("The solution of the system is:")
print(x)

[[ 1.00000000e+00 -1.00000000e+00  4.00000000e+00  0.00000000e+00
   2.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  5.00000000e+00 -2.00000000e+00  7.00000000e+00
   8.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -7.00000000e+00 -2.80000000e+01
   3.00000000e+00  5.90000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.66000000e+01
   1.00000000e+01  7.65000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.55271368e-15
   3.61886792e+00 -8.17547170e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -1.70870894e+01]]
[19.          2.         32.         75.05        6.14811321 -2.59437528]
The solution of the system is:
[-1.76181704  0.89622803  4.0519314  -1.6171308   2.04191354  0.15183249]


In [ ]:
from numpy import array, zeros, fabs, linalg
a = array([[1,-1,4,0,2,9],
           [0,5,-2,7,8,4],
           [1,0,5,7,3,-2],
           [6,-1,2,3,0,8],
           [-4,2,0,5,-5,3],
           [0,7,-1,5,4,-2]], float)
#the b matrix constant terms of the equations 
b = array([19,2,13,-7,-9,2], float)
n = len(b)
x = zeros(n, float)

#first loop specifys the fixed row
for k in range(n-1):
    if fabs(a[k,k]) < 1.0e-12:
        for i in range(k+1, n):
            if fabs(a[i,k]) > fabs(a[k,k]):
                a[[k,i]] = a[[i,k]]

                break

 #applies the elimination below the fixed row

    for i in range(k+1,n):
        if a[i,k] == 0:continue

        factor = a[k,k]/a[i,k]
        for j in range(k,n):
            a[i,j] = a[k,j] - a[i,j]*factor
            #we also calculate the b vector of each row
        b[i] = b[k] - b[i]*factor
print(a)



x[n-1] = b[n-1] / a[n-1, n-1]
for i in range(n-2, -1, -1):
    sum_ax = 0
  
    for j in range(i+1, n):
        sum_ax += a[i,j] * x[j]
        
    x[i] = (b[i] - sum_ax) / a[i,i]

print("The solution of the system is:")
print(x)

In [7]:
print(len(a))

6


In [3]:
print("Solution by NumPy:")


print(linalg.solve(a, b))

Solution by NumPy:
[-1.76181704  0.89622803  4.0519314  -1.6171308   2.04191354  0.15183249]
